apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

helmCharts:
  - name: prefect-server
    repo: https://prefecthq.github.io/prefect-helm
    version: 2025.11.21180339
    valuesFile: values.yaml
    releaseName: prefect-server
    namespace: default
    includeCRDs: true

resources:
  - secrets.yaml
