---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prefect-admin-credentials
spec:
  encryptedData:
    auth-string: AgCevZBlXlCIJFJHK2ft1fZzLpzrV14zGlFB7+k7UbgWIoevYJbX9k4i0+lFBlu74Ea9mmE3m/chovHIu0e51D4GGpM6mNJPWu2Lk/Nn5N5c5x1DWlEFmfik+HVhEjK9nSmwhExSjQ0tvtiFu57r5kk69dp0nxIdhYdfTgZPnYgtUq/MZcdR5ft+4hiGC/ZtoiyKkDZ+KYJG4HxjLEsGnPXj0oHSgRKH7RqkWGCC7tDDxdjy2lCJ4lTs54VXJh91K/14H2CQCKSGOBjBskxl5Db9oYZZ3EDRp7sJulJMa/54miOB5W9DILwsL/Npaun/Scrf2H+xRk9jODL9dew/B98AnjWMJr8+05CpmRM1XdQfQI9pjUynNkUZZpimiDA1Wogvtzkh2LTvjiH5wdL/NoPRWS10p2pLN6sBZR00lVlpDxLm0h0tW+WH4DOuxQVeIPpumZkRArIniKY3OD/FemJ4L/uN8JtXdGzxHoYZdgj6JDz6yAD2w+qcYOvpSQXYLqhWVxG7ph41gSwE0aBVuco88CDSMzZdHKF2IQ2ZUpOStiunVFUcdqB+Zn+DlVJNf3KEpCrhbGcPzZai23tqzubO9r0G85+IAys3qorpO8eDmtlGIOt+AxGKV+OheV9qS0q6pEfdJ0S4jFzkTJhMvEzyFPB3WuGGWn75JGnXRtjqy8mJCcPrsbPlCRPDG+RK7887Bn4ygbNCOW+yo9brXA==
  template:
    metadata:
      name: prefect-admin-credentials
      namespace: default
